### PR TITLE
Create EventEmitterAwareTrait.php

### PR DESCRIPTION
**Pull request by renanbr**

### CODE REVIEW

**Comment by kelunik** [comment]
Why should something like that be in this package?

**Comment by WyriHaximus** [comment]
Have to agree with @kelunik here, this is beyond the scope of this package being concise and simple. None the less your efforts are appreciated.

**Comment by renanbr** [comment]
Just for registering the history of this PR: A long time ago I used it to inject the EventEmitter into the services that implement this interface through a factory, like the autowire from Symfony do nowadays.

Thanks for reviewing, for my current usage this interface isn't necessary anymore.

**Comment by WyriHaximus** [comment]
Thank you for the update, and my apologise for the late response. Took maintenance over last night so making my way though all issues and PRs to get releases out tomorrow.

**Pull request closed without merging**
