### PR TITLE
Less complicated off

### PR DESCRIPTION
**Pull request by WyriHaximus**
Followup of #52 making the code slightly less complicated and easier on the mind.

### CODE REVIEW

**Comment by calcinai** [comment]
Doesn't this PR invert the logic of the `if` statement?

**Comment by WyriHaximus** [comment]
It does 0_o. Time to revisit it and add tests for this 🤐

**Comment by calcinai** [comment]
Whoops! I only looked at the change in the first place out pure of curiosity.

**Comment by andig** [comment]
Ping @WyriHaximus shouldn‘t this be reverted in the mean time as its currently broken?

**Comment by WyriHaximus** [comment]
@andig this has been solved in #58, both haven't been released yet tho

**Pull request merged**
